url: https://uvaclimatestories.com
baseurl: /
host: 0.0.0.0
exclude:
  - .gitignore
  - CNAME
  - LICENSE
  - Makefile
  - README.md
  - docker-compose.yml
  - docker-compose-auto.yml
  - launch.sh
  - update_website.sh
  - Gemfile
  - Gemfile.lock
title: UVA Climate Stories
sass:
  sass_dir: _sass
collections:
  stories:
    output: true
    permalink: /:collection/:title
collections_dir: pages
defaults:
  - scope:
      path: ''
      type: stories
    values:
      layout: story
      css: /assets/styles/story.css
