version: '3'
services:
  web:
    image: jekyll/jekyll
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    command: sh -c "bundle install && make run"
    container_name: web
    tty: true
    stdin_open: true
